src/Entity/Workout.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WorkoutRepository")
 * @ORM\Table(name="tbl_workout")
 */
class Workout
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Quizz")
     * @ORM\JoinColumn(nullable=false)
     */
    private $quizz;

    /**
     * @ORM\Column(type="datetime")
     */
    private $started_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $ended_at;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $current_question_number;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $last_question_id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $completed;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $score;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuizz(): ?Quizz
    {
        return $this->quizz;
    }

    public function setQuizz(?Quizz $quizz): self
    {
        $this->quizz = $quizz;

        return $this;
    }

    public function getStartedAt(): ?\DateTimeInterface
    {
        return $this->started_at;
    }

    public function setStartedAt(\DateTimeInterface $started_at): self
    {
        $this->started_at = $started_at;

        return $this;
    }

    public function getEndedAt(): ?\DateTimeInterface
    {
        return $this->ended_at;
    }

    public function setEndedAt(?\DateTimeInterface $ended_at): self
    {
        $this->ended_at = $ended_at;

        return $this;
    }

    public function getCurrentQuestionNumber(): ?int
    {
        return $this->current_question_number;
    }

    public function setCurrentQuestionNumber(?int $current_question_number): self
    {
        $this->current_question_number = $current_question_number;

        return $this;
    }

    public function getLastQuestionId(): ?int
    {
        return $this->last_question_id;
    }

    public function setLastQuestionId(?int $last_question_id): self
    {
        $this->last_question_id = $last_question_id;

        return $this;
    }

    public function getCompleted(): ?bool
    {
        return $this->completed;
    }

    public function setCompleted(bool $completed): self
    {
        $this->completed = $completed;

        return $this;
    }

    public function getScore(): ?float
    {
        return $this->score;
    }

    public function setScore(?float $score): self
    {
        $this->score = $score;

        return $this;
    }
}

src/Form/WorkoutType.php
<?php

namespace App\Form;

use App\Entity\Workout;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class WorkoutType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('started_at')
            ->add('ended_at')
            ->add('current_question_number')
            ->add('last_question_id')
            ->add('completed')
            ->add('score')
            ->add('quizz')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Workout::class,
        ]);
    }
}

src/Controller/WorkoutController.php
<?php

namespace App\Controller;

use App\Entity\Workout;
use App\Form\WorkoutType;
use App\Repository\WorkoutRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

/**
 * @Route("/workout")
 */
class WorkoutController extends AbstractController
{
    /**
     * @Route("/", name="workout_index", methods={"GET"})
     */
    public function index(WorkoutRepository $workoutRepository): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        return $this->render('workout/index.html.twig', [
            'workouts' => $workoutRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id}/new", name="workout_new", methods={"GET","POST"})
     */
    public function new(Request $request, int $id, EntityManagerInterface $em): Response
    {
        $this->denyAccessUnlessGranted('ROLE_USER');
        $workout = new Workout();
        $form = $this->createForm(WorkoutType::class, $workout);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($workout);
            $entityManager->flush();

            return $this->redirectToRoute('workout_index');
        }

        return $this->render('workout/new.html.twig', [
            'workout' => $workout,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="workout_show", methods={"GET"})
     */
    public function show(Workout $workout): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        return $this->render('workout/show.html.twig', [
            'workout' => $workout,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="workout_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Workout $workout): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        $form = $this->createForm(WorkoutType::class, $workout);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('workout_index');
        }

        return $this->render('workout/edit.html.twig', [
            'workout' => $workout,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="workout_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Workout $workout): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        if ($this->isCsrfTokenValid('delete'.$workout->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($workout);
            $entityManager->flush();
        }

        return $this->redirectToRoute('workout_index');
    }
}

templates/workout/_delete_form.html.twig
<form method="post" action="{{ path('workout_delete', {'id': workout.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ workout.id) }}">
    <button class="btn">Delete</button>
</form>

templates/workout/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/workout/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Workout{% endblock %}

{% block body %}
    <h1>Edit Workout</h1>

    {{ include('workout/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('workout_index') }}">back to list</a>

    {{ include('workout/_delete_form.html.twig') }}
{% endblock %}

templates/workout/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Workout index{% endblock %}

{% block body %}
    <h1>Workout index</h1>

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Started_at</th>
                <th>Ended_at</th>
                <th>Current_question_number</th>
                <th>Last_question_id</th>
                <th>Completed</th>
                <th>Score</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for workout in workouts %}
            <tr>
                <td>{{ workout.id }}</td>
                <td>{{ workout.startedAt ? workout.startedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ workout.endedAt ? workout.endedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ workout.currentQuestionNumber }}</td>
                <td>{{ workout.lastQuestionId }}</td>
                <td>{{ workout.completed ? 'Yes' : 'No' }}</td>
                <td>{{ workout.score }}</td>
                <td>
                    <a href="{{ path('workout_show', {'id': workout.id}) }}">show</a>
                    <a href="{{ path('workout_edit', {'id': workout.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('workout_new') }}">Create new</a>
{% endblock %}

templates/workout/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Workout{% endblock %}

{% block body %}
    <h1>Create new Workout</h1>

    {{ include('workout/_form.html.twig') }}

    <a href="{{ path('workout_index') }}">back to list</a>
{% endblock %}

templates/workout/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Workout{% endblock %}

{% block body %}
    <h1>Workout</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ workout.id }}</td>
            </tr>
            <tr>
                <th>Started_at</th>
                <td>{{ workout.startedAt ? workout.startedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Ended_at</th>
                <td>{{ workout.endedAt ? workout.endedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Current_question_number</th>
                <td>{{ workout.currentQuestionNumber }}</td>
            </tr>
            <tr>
                <th>Last_question_id</th>
                <td>{{ workout.lastQuestionId }}</td>
            </tr>
            <tr>
                <th>Completed</th>
                <td>{{ workout.completed ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Score</th>
                <td>{{ workout.score }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('workout_index') }}">back to list</a>

    <a href="{{ path('workout_edit', {'id': workout.id}) }}">edit</a>

    {{ include('workout/_delete_form.html.twig') }}
{% endblock %}