src/Entity/Quizz.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\QuizzRepository")
 * @ORM\Table(name="tbl_quizz")
 */
class Quizz
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $summary;

    /**
     * @ORM\Column(type="integer")
     */
    private $number_of_questions;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="quizzes")
     */
    private $categories;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
        $this->setUpdatedAt(new \DateTime());
        $this->categories = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(?string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getNumberOfQuestions(): ?int
    {
        return $this->number_of_questions;
    }

    public function setNumberOfQuestions(int $number_of_questions): self
    {
        $this->number_of_questions = $number_of_questions;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->title;
    }

}

src/Form/QuizzType.php
<?php

namespace App\Form;

use App\Entity\Quizz;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Category;

class QuizzType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('summary')
            ->add('number_of_questions')
            ->add('active')
        ;

        $builder->add('categories', EntityType::class, array(
            'class' => Category::class,
            'choice_label' => 'longname',
            'multiple' => true
        ));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Quizz::class,
        ]);
    }
}

src/Controller/QuizzController.php
<?php

namespace App\Controller;

use App\Entity\Quizz;
use App\Form\QuizzType;
use App\Repository\QuizzRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @Route("/quizz")
 */
class QuizzController extends AbstractController
{    
    /**
     * @Route("/", name="quizz_index", methods={"GET"})
     */
    public function index(QuizzRepository $quizzRepository): Response
    {
        return $this->render('quizz/index.html.twig', [
            'quizzs' => $quizzRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="quizz_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $quizz = new Quizz();
        $form = $this->createForm(QuizzType::class, $quizz);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($quizz);
            $entityManager->flush();

            return $this->redirectToRoute('quizz_index');
        }

        return $this->render('quizz/new.html.twig', [
            'quizz' => $quizz,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="quizz_show", methods={"GET"})
     */
    public function show(Quizz $quizz): Response
    {
        return $this->render('quizz/show.html.twig', [
            'quizz' => $quizz,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="quizz_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Quizz $quizz): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        
        $quizz->setUpdatedAt(new \DateTime());

        $form = $this->createForm(QuizzType::class, $quizz);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('quizz_index');
        }

        return $this->render('quizz/edit.html.twig', [
            'quizz' => $quizz,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="quizz_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Quizz $quizz): Response
    {
        if ($this->isCsrfTokenValid('delete'.$quizz->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($quizz);
            $entityManager->flush();
        }

        return $this->redirectToRoute('quizz_index');
    }
}

templates/quizz/_delete_form.html.twig
<form method="post" action="{{ path('quizz_delete', {'id': quizz.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ quizz.id) }}">
    <button class="btn">Delete</button>
</form>

templates/quizz/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/quizz/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Quizz{% endblock %}

{% block body %}
    <h1>Edit Quizz</h1>

    {{ include('quizz/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('quizz_index') }}">back to list</a>

    {{ include('quizz/_delete_form.html.twig') }}
{% endblock %}

templates/quizz/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quizz index{% endblock %}

{% block body %}
    <h1>Quizz index</h1>

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Categories</th>
                <th>Summary</th>
                <th>Number_of_questions</th>
                <th>Active</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for quizz in quizzs %}
            <tr>
                <td>{{ quizz.id }}</td>
                <td>{{ quizz.title }}</td>
                <td>
                    {% for categorie in quizz.categories %}
                    {{ categorie.shortname}}
                    {% endfor %}
                </td>
                <td>{{ quizz.summary }}</td>
                <td>{{ quizz.numberOfQuestions }}</td>
                <td>{{ quizz.active ? 'Yes' : 'No' }}</td>
                <td>
                    <a class="btn btn-outline-success fa fa-eye" href="{{ path('quizz_show', {'id': quizz.id}) }}"></a>
                    <a class="btn btn-outline-success fa fa-pencil" href="{{ path('quizz_edit', {'id': quizz.id}) }}"></a>
                    <a class="btn btn-outline-success fa fa-play-circle" href="{{ path('workout_new', {'id': quizz.id}) }}"></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-outline-success" href="{{ path('quizz_new') }}">Create new</a>
{% endblock %}

templates/quizz/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Quizz{% endblock %}

{% block body %}
    <h1>Create new Quizz</h1>

    {{ include('quizz/_form.html.twig') }}

    <a href="{{ path('quizz_index') }}">back to list</a>
{% endblock %}

templates/quizz/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Quizz{% endblock %}

{% block body %}
    <h1>Quizz</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ quizz.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ quizz.title }}</td>
            </tr>
            <tr>
                <th>Summary</th>
                <td>{{ quizz.summary }}</td>
            </tr>
            <tr>
                <th>Number_of_questions</th>
                <td>{{ quizz.numberOfQuestions }}</td>
            </tr>
            <tr>
                <th>Catégories</th>
                <td>
                    {% for categorie in quizz.categories %}
                    {{ categorie.shortname}}
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ quizz.active ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('quizz_index') }}">back to list</a>

    <a href="{{ path('quizz_edit', {'id': quizz.id}) }}">edit</a>

    {{ include('quizz/_delete_form.html.twig') }}
{% endblock %}